# Using the official PostgreSqQL image from the Docker Hub
# postgres:14 is one of the latest versions of PostgreSQL on docker hub
# it should be noted that postgres:14 also has concerning vulnerabilities
FROM postgres:14
