version: '3.8'

services:
  Babelr_db:
    image: postgres:14
    container_name: Babelr
    environment:
      POSTGRES_USER: Babelr
      POSTGRES_PASSWORD: W16B3900 # Change this to your own password in PROD, additionally do not hardcode passwords in PROD
      POSTGRES_DB: Babelr_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  
      # Persists data even after container is stopped or removed by using docker commands
      # (persistence will work if using docker-compose down to remove containers)
      # (persistence does not work if using docker-compose down -v; -v flag removes volumes)
    networks:
      - app_network

  web:
    build: ./backend
    environment:                  # dont hardcode environment variables in PROD
      POSTGRES_USER: Babelr
      POSTGRES_PASSWORD: W16B3900 # Change this to your own password in PROD
      POSTGRES_DB: Babelr_db
      POSTGRES_HOST: Babelr_db
    ports:
      - "8016:8016"
    depends_on:
      - Babelr_db
    env_file:
      - .env
    networks:
      - app_network
    volumes:
      - ./audioData:/app/audioData:rw   
      # Mounts the audioData folder to the container
      # this can be updated to the proper method when integrating with a cloud storage service
      # (e.g. AWS S3, Google Cloud Storage, Azure Blob Storage)   

  frontend:
    build: ./frontend/babelr
    ports:
      - "3000:3000"
    depends_on:
      - web
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:8016
    env_file:
      - .env

volumes:
  postgres_data:
    driver: local

networks:
  app_network: